version: "3.9"

networks:
  local:
    driver: bridge

services:
  db:
    image: postgres
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_PASSWORD=Pass1234
    ports:
      - "5432:5432"
    networks:
      - local

  dbadmin:
    image: dpage/pgadmin4
    volumes:
      - ./servers.json:/pgadmin4/servers.json
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@local.com
      - PGADMIN_DEFAULT_PASSWORD=Pass1234
    ports:
      - "5050:80"
    networks:
      - local
